apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
        - name: frontend
          resources:
            limits:
              memory: '350Mi'
              cpu: '300m'
            requests:
              memory: '250Mi'
              cpu: '200m'
          image: yangricardo/hf-k8s-web:latest
          imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  type: ClusterIP
  ports:
    - name: 'frontend'
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: frontend
