NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-org3-9054-ca-org3.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-org3-9054-ca-org3.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-org3-9054-ca-org3.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-org3-9054-ca-org3.pem
    OrganizationalUnitIdentifier: orderer
