--- #---------------- Chaincode Service ---------------------
apiVersion: v1
kind: Service
metadata:
  name: fabric-es-chaincode-org1
  labels:
    app: fabric-es-chaincode-org1
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: fabric-es-chaincode-org1
