apiVersion: v1
kind: Pod
metadata:
  name: hf-on-k8s-course-pv-pod
  labels:
    app: hf-on-k8s-course-pv
spec:
  containers:
    - name: hf-on-k8s-course-pv-container
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: hf-on-k8s-course-volume
  volumes:
    - name: hf-on-k8s-course-volume
      persistentVolumeClaim:
        claimName: hf-on-k8s-course
